import os, sys
sys.path.append('/var/www/MediVol/')
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "MediVol.settings")
from django.db import models
from catalog.models import Category, BoxName, Item

print 'beginning initialization of categories'

letter_mapping = (
    #(letter, name),
    ('A', 'Mother and Child'),
    ('B', 'Personal Care'),
    ('C', 'Patient Care'),
    ('D', 'Laboratory'),
    ('E', 'Provider Protection'),
    ('F', 'Pertaining to the Head'),
    ('G', 'Respiratory: Tracheostomy'),
    ('H', 'Respiratory: Oxygen'),
    ('I', 'Cardiovascular'),
    ('J', 'Digestive System'),
    ('K', 'Urinary'),
    ('L', 'Drains and Suction'),
    ('M', 'Dressings'),
    ('N', 'Ortho'),
    ('O', 'Syringes'),
    ('P', 'Needles'),
    ('Q', 'IV Supplies'),
    ('R', 'Anesthesia'),
    ('S', 'Sutures'),
    ('T', 'Cautery'),
    ('U', 'Surgical Linens'),
    ('V', 'Surgical Miscellanea'),
    ('W', 'Surgical Supplies'),
    ('X', 'Plastic'),
    ('Y', 'UNKNOWN'),
    ('Z', 'LittleThings'))
categories = Category.objects.all()
categories.delete()

for pair in letter_mapping:
    category = Category(letter=pair[0], name=pair[1])
    category.save()

box_name = BoxName.objects.all()
box_name.delete()

box_name_mapping = (
    #(box name, category letter, does it expire, do we count it)
    ('Adult Diapers','B',False,False),
    ('OB Pads','A', True,False),
    ('OB/GYN Mix','A', True,False),
    ('Pediatric Diapers','A', True,False),
    ('Pediatric Supplies','A', True,False),
    ('Speculums','A',False,True),
    ('Anti-Embolism Stockings','B', True,True),
    ('Oral Care','B', True,False),
    ('Personal Care','B', True,False),
    ('Slippers','B',False,False),
    ('Under Pads/Chux (Cloth)','B',False,True),
    ('Under Pads/Chux (Disposable)','B',False,False),
    ('Blood Pressure Cuffs/Stethoscopes','C',False,True),
    ('Diabetic Glucometers','C', True,True),
    ('Diabetic Supplies','C', True,True),
    ('Foam','C', True,True),
    ('Patient Care','C', True,False),
    ('Probe Covers','C', True,True),
    ('Bed Linens','C',False,False),
    ('Immobilizers','C',False,True),
    ('Patient Gowns','C',False,True),
    ('Poseys (Vest, Wrist)','C',False,True),
    ('Positioning Devices','C',False,True),
    ('Shrouds','C',False,True),
    ('Blood Collection/Vacutainer Supplies','D', True,False),
    ('Exam Table Paper','C',False,False),
    ('Hats/Head Covers','E', True,False),
    ('Lab Supplies','D', True,False),
    ('Masks','E', True,False),
    ('Specimen Containers','D', True,False),
    ('Gloves (Sterile)','E', True,True),
    ('Gloves (Unsterile, Boxed)','E', True,True),
    ('Gloves (Unsterile, Loose)','E', True,True),
    ('Gowns (Unsterile, Paper)','E', True,True),
    ('Shoe Covers','E', True,False),
    ('Dental Surgery','F', True,False),
    ('ENT (Ears, Nose, Throat)','F', True,False),
    ('Eye Care','F', True,False),
    ('Gowns (Sterile, Paper)','E', True,True),
    ('Ophthalmic Surgery','F', True,False),
    ('Misc. Tracheostomy Supplies','G', True,False),
    ('Respiratory Mix','H', True,False),
    ('Tracheostomy Care Kits','G', True,True),
    ('Tracheostomy Tubes','G', True,True),
    ('Ambu Bags (Adult)','H',False,True),
    ('Ambu Bags (Pediatric)','H',False,True),
    ('Bronchoscopy Biopsy Forceps/Brushes','H', True,False),
    ('O2 Nasal Cannulas & Masks','H',False,True),
    ('Oxygen Tubing','H',False,True),
    ('Airway','H', True,False),
    ('CPAP','H', True,False),
    ('Humidifiers','H', True,True),
    ('Nebulizers','H', True,True),
    ('O2 Gauges & Supplies','Z',False,True),
    ('Cardiovascular Mix','I', True,False),
    ('Defibrillator Pads','I', True,False),
    ('EKG Electrodes','I', True,False),
    ('Endoscopy','J', True,False),
    ('Heart Cannulas','I', True,False),
    ('Enema','J', True,False),
    ('Feeding & Kangaroo Bags','J', True,True),
    ('Feeding Tubes','J', True,False),
    ('Misc. Urine Collection','K', True,False),
    ('Ostomy Care Supplies','J', True,False),
    ('Ostomy Supplies','J', True,False),
    ('Catheters (Foley, Straight, Texas)','K', True,False),
    ('Dialysis','K', True,False),
    ('Nasogastric (NG) Tubes','J', True,False),
    ('Urinary Catheter Trays/Kits','K', True,True),
    ('Urinary Drainage Bags','K', True,True),
    ('Urology Mix','K', True,False),
    ('Chest Drains','L', True,True),
    ('Jackson-Pratt Drains','L', True,True),
    ('Suction Canisters','L', True,True),
    ('Suction Catheters','L', True,False),
    ('Suction Tubing','L', True,True),
    ('Yankauer/Frazier Tips','L', True,True),
    ('Bulb Syringes/Funnels','L', True,True),
    ('Drainage Kits','L', True,True),
    ('Drains','L', True,True),
    ('Irrigation','T', True,True),
    ('Roll Gauze','M', True,False),
    ('Wound Care','M', True,False),
    ('Ace Bandages','M',False,False),
    ('Coban','M', True,False),
    ('Dressings (Sterile, Non-medicated)','M', True,False),
    ('Dressings (Sterile, Treated/Medicated)','M', True,False),
    ('Dressings (Unsterile)','M', True,False),
    ('Tegaderm','M', True,False),
    ('Cast Padding','N', True,True),
    ('Casting Tape','N', True,True),
    ('Ortho Drills & Saw Blades','N', True,False),
    ('Orthopedic Mix','N', True,False),
    ('Shoulder/Elbow Suspension Kits','N', True,False),
    ('Tan Stockinettes','N',False,True),
    ('Insulin Syringes','O', True,False),
    ('Syringes - 1-3cc (Sterile)','O', True,False),
    ('Syringes - 10cc (Sterile)','O', True,False),
    ('Syringes - 20-60cc (Sterile)','O', True,False),
    ('Syringes - 5cc (Sterile)','O', True,False),
    ('Oral Dosing Syringes','O', True,False),
    ('Port Access Needles','P', True,True),
    ('Angio-Catheters','P', True,True),
    ('Butterfly Catheters','P', True,True),
    ('Needles','P', True,False),
    ('Spinal Needles','P', True,True),
    ('Syringes-All Sizes (Unsterile)','O', True,False),
    ('Central Line & Swan Ganz Kits','Q', True,False),
    ('Central Line Supplies','Q', True,False),
    ('IV Mix','Q', True,False),
    ('IV Starter Kits','Q', True,True),
    ('IV Tubing','Q', True,False),
    ('Anesthesia Masks/Circuits','R', True,True),
    ('Anesthesia Mix','R', True,False),
    ('Endotracheal Tubes/LMAs/ Stylettes','R', True,True),
    ('Esmark for Tourniquets','R', True,True),
    ('Tourniquet Cuffs','R', True,True),
    ('Ventilator Tubing','R', True,True),
    ('Needle Box','S', True,True),
    ('Skin Staplers (Sterile)','T', True,True),
    ('Skin Staplers (Unsterile)','T', True,True),
    ('Suture/Staple Removal','S', True,True),
    ('Sutures (Expired)','S',False,False),
    ('Sutures (Unexpired)','S', True,False),
    ('Cautery Supplies','T', True,True),
    ('Laceration Kits','T', True,True),
    ('Surgical Drapes (Sterile)','U', True,True),
    ('Surgical Packs (Sterile)','U', True,True),
    ('Misc. OR Supplies (Sterile)','W', True,True),
    ('OR Suction Supplies (Sterile)','W', True,True),
    ('Skin Markers','T', True,False),
    ('Surgical Sheets (Sterile)','U', True,True),
    ('Autoclave Wraps','U',False,True),
    ('Mayo Stand Covers (Unsterile)','U', True,True),
    ('Sheets (Unsterile, Paper)','U', True,True),
    ('Sheets (Unsterile, Plastic)','U', True,True),
    ('Under Buttocks Drapes','U', True,True),
    ('Drapes (Unsterile, Large)','U', True,True),
    ('Drapes (Unsterile, Small)','U', True,True),
    ('Quarter Drapes','U', True,True),
    ('Tail Drapes','U', True,True),
    ('Lap Sponges (Sterile)','V', True,True),
    ('Lap Sponges (Unsterile)','V', True,False),
    ('Raytex (Sterile)','V', True,True),
    ('Raytex (Unsterile)','V', True,False),
    ('Towels (Unsterile, Cloth)','V', True,True),
    ('Towels (Unsterile, Paper)','V', True,False),
    ('Foam Sponges','W', True,False),
    ('Impervious Stockinettes (Unsterile)','W', True,True),
    ('Magnetic Instrument Pads','W',False,True),
    ('Scrub Brushes','W', True,True),
    ('Skin Prep','W', True,True),
    ('Biopsy Kits','P', True,True),
    ('Mesh Mix','W', True,False),
    ('Neurology Mix','W', True,False),
    ('Steri-Drapes/Ioban','W', True,True),
    ('Sterilization Pouches','W',False,True),
    ('Surgical Patties/Tonsil Sponges','W', True,False),
    ('Other Plastics','X', True,True),
    ('Pill Bottles','X',False,False),
    ('Plastic Trays','X',False,True),
    ('Cautery Sticks','Z', True,True),
    ('Tourniquets','Z', True,False),
    #('Batteries','NONE',False,False),
    ('Peanuts, Kitners (Sterile)','Z', True,True),
    ('Applicator Appliers & Clips (Hemo Clips)','Z', True,True),
    ('DermaHooks','Z', True,False),
    ('Mastisol/ Dermabond','Z', True,False),
    ('Safety Pins, Sterile Rubber Bands, Suture Aid Booties','Z', True,False),
    ('Tape & Tape Remover','Z', True,False),
    ('Umbilical Tape, Polyester Tape, Silicone Clamp Covers, Retro Tape','Z', True,False),
    ('Bone Wax, Gelfoam, Surgifoam, Avitene, Surgicel','Z', True,False),
    ('Alcohol Prep Pads & Swabsticks','Z', True,False),
    ('Antiseptic Gel Hand Rinse','Z', True,False),
    ('Cotton Balls','Z', True,False),
    ('Povidone-Iodine & Swabstick','Z', True,False),
    ('Povidone-Iodine Pads','Z', True,False),
    ('Povidone-Iodine Solution & Ointment','Z', True,False),
    ('Povidone-Iodine Sponges & Sponges w/ Sticks','Z', True,False),
    ('Thermometers','Z', True,True),
    ('Chlorascrub Swabs & Swabsticks','Z', True,False),
    ('Antiseptic  & Cleansing Towelettes','Z', True,False),
    ('Compound Benzoin Tincture Swabsticks','Z', True,False),
    ('Skin Protectant Swabsticks','Z', True,False),
    ('Skin Prep Pads & Protective Barrier Wipes','Z', True,False),
    ('Petroleum Jelly','Z', True,False),
    ('Q-Tips & Cotton-Tipped Applicators','Z', True,False),
    ('Tongue Depressors','Z', True,False),
    ('Band-Aids, Steri-Strips','Z', True,False),
    ('Blades/Scalpels','Z', True,False),
    ('Fish/Bowel Protector','Z', True,False),
    ('Goggles','Z', True,True),
    ('Hot/Cold Packs','Z', True,True),
    ('Lubricating Gel & Surgical Lubricant','Z', True,False),
    ('Spill Kits','Z', True,True),
    ('Ultrasound Gel','Z', True,False)
    )

for pair in box_name_mapping:
    box_name = BoxName(name=pair[0], category=Category.objects.get(letter=pair[1]), can_expire=pair[2], can_count=pair[3])
    box_name.save()

item_file = file('/var/www/MediVol/catalog/test_item_list.txt', 'r')
box_name = None
for line in item_file:
    if ':' in line:
        box_name = BoxName.objects.get(name=line.split(":")[0]) 
    else:
        item = Item(box_name=box_name, name=line.strip(), description='')
        item.save()   
